{% set version = "2.7.3" %}

package:
  name: protozfits
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/protozfits/protozfits-{{ version }}.tar.gz
  sha256: 187dadf2af59e4b471cd802139e41fa8cc9162bd9943aa3fd90028ed88a860f1

build:
  number: 0
  script:
    - export CMAKE_ARGS="${CMAKE_ARGS} -Dprotobuf_generate_PROTOC_EXE=$BUILD_PREFIX/bin/protoc"  # [build_platform != target_platform]
    - {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  skip: true  # [win or python_impl == 'pypy' or py<39]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    # for enabling m1 cross compilation
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - protobuf                               # [build_platform != target_platform]
    - libprotobuf                            # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - scikit-build-core                      # [build_platform != target_platform]
    - setuptools_scm                         # [build_platform != target_platform]
    - zeromq                                 # [build_platform != target_platform]
    - zlib                                   # [build_platform != target_platform]
    - zstd                                   # [build_platform != target_platform]
  host:
    - pip
    - python
    - protobuf
    - libabseil
    - libprotobuf
    - pybind11
    - scikit-build-core
    - setuptools_scm
    - zeromq
    - zlib
    - zstd
  run:
    - astropy-base
    - numpy
    - protobuf
    - python
    - zeromq
    - zlib
    - tqdm
    - zstd

test:
  imports:
    - protozfits
    - protozfits.rawzfits
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cta-observatory.org/cta-computing/common/acada-array-elements/adh-apis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python bindings the CTA zfits reader
  description: |
    protozfits are the python bindings for reading the protozfits raw data format,
    which is a prototype raw data format build in FITS and Protocol Buffers for
    the data of the Cherenkov Telescope Array.
  dev_url: https://gitlab.cta-observatory.org/cta-computing/common/acada-array-elements/adh-apis

extra:
  recipe-maintainers:
    - maxnoe
    - dneise
