{% set version = "2.4.0" %}

package:
  name: protozfits
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/protozfits/protozfits-{{ version }}.tar.gz
  sha256: 242e782d1eb7983d7180eb6eeb6d001eac09a02b45f8af169c9647adc639b963
  patches:
    - patches/0001-Add-support-for-CMAKE_ARGS-in-setup.py-to-enable-con.patch
    - patches/0002-compatibility-with-C-17.patch
    - patches/0003-do-not-enforce-old-protobuf-version-in-installation-.patch
    - patches/0004-ensure-DProtobuf_PROTOC_EXECUTABLE-.-is-respected.patch

build:
  number: 0
  script:
    - export CMAKE_ARGS="${CMAKE_ARGS} -DProtobuf_PROTOC_EXECUTABLE=$BUILD_PREFIX/bin/protoc"  # [build_platform != target_platform]
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make   # [not win]
    - ninja  # [win]
    # for enabling m1 cross compilation
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - protobuf                               # [build_platform != target_platform]
    - libprotobuf                            # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]
    - zeromq                                 # [build_platform != target_platform]
    - zlib                                   # [build_platform != target_platform]
  host:
    - pip
    - python
    - protobuf
    - libabseil
    - libprotobuf
    - setuptools
    - zeromq
    - zlib
  run:
    - astropy
    - numpy
    - protobuf
    - python
    - zeromq
    - zlib

test:
  imports:
    - protozfits
    - protozfits.rawzfits
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cta-observatory.org/cta-computing/common/acada-array-elements/adh-apis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python bindings the CTA zfits reader
  description: |
    protozfits are the python bindings for reading the protozfits raw data format,
    which is a prototype raw data format build in FITS and Protocol Buffers for
    the data of the Cherenkov Telescope Array.
  dev_url: https://gitlab.cta-observatory.org/cta-computing/common/acada-array-elements/adh-apis

extra:
  recipe-maintainers:
    - maxnoe
    - dneise
