{% set name = "protozfits" %}
{% set version = "2.0.1.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3864c6097196208fca15b17eb49241675b3811bd6d1ffec206ce0e3bba8f89f
  patches:
    - 0001-Add-support-for-CMAKE_ARGS-in-setup.py-to-enable-con.patch

build:
  number: 8
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win]
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make   # [not win]
    - ninja  # [win]
    # for enabling m1 cross compilation
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - protobuf                               # [build_platform != target_platform]
    - libprotobuf                            # [build_platform != target_platform]
    - setuptools                             # [build_platform != target_platform]
    - zeromq                                 # [build_platform != target_platform]
    - zlib                                   # [build_platform != target_platform]
  host:
    - pip
    - python
    - protobuf
    - libprotobuf
    - setuptools
    - zeromq
    - zlib
  run:
    - astropy
    - numpy
    - protobuf
    - python
    - zeromq
    - zlib

test:
  imports:
    - protozfits
    - protozfits.rawzfitsreader
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cta-observatory.org/cta-computing/common/acada-array-elements/adh-apis
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python bindings the CTA zfits reader'
  description: |
    protozfits are the python bindings for reading the protozfits raw data format,
    which is a prototype raw data format build in FITS and Protocol Buffers for
    the data of the Cherenkov Telescope Array.
  dev_url: https://gitlab.cta-observatory.org/cta-computing/common/acada-array-elements/adh-apis

extra:
  recipe-maintainers:
    - maxnoe
    - dneise
